### ISSUE TITLE
Hamburger not working

### ISSUE THREAD

**Issue by nitin-pandita** [himanshu251001/E-Commerce#12]

**Comment by himanshu251001** [comment]
> _No description provided._

What is that?

**Comment by nitin-pandita** [comment]
The three line on left side

**Comment by rahulrana701** [comment]
@himanshu251001 basically the navbar is not working properly the hamburger (three lines on left side is not working properly)
if you want I can work on this issue....

**Comment by himanshu251001** [comment]
Okay go ahead and also look why traditional page is not working. 
@RahulRana701 @nitin-pandita

**Comment by himanshu251001** [comment]
As Hackodex is ending soon, whoever solves the problem first there pr will be merged
