### ISSUE TITLE
Update the UI of the StoneWork Page 

### ISSUE THREAD

**Issue by himanshu251001** [himanshu251001/E-Commerce#3]
Make the UI more responsive and attractive  according to the Home Page

**Comment by charvibhargava** [comment]
Please assign this to me.

**Comment by himanshu251001** [comment]
> Please assign this to me.

Okay go ahead.

**Comment by charvibhargava** [comment]
i have created the pull request, please verify. @himanshu251001

**Comment by himanshu251001** [comment]
> i have created the pull request, please verify. @himanshu251001

@charvibhargava Nice Work Done. Can You Make The UI A bit Colorful and this a problem in responsiveness.The Bar buttons are come over the text on minimising.Give it shot then i will merge the request

**Comment by charvibhargava** [comment]
@himanshu251001 i've worked on the responsiveness of the page. please verify.

**Comment by charvibhargava** [comment]
Please add the label of hackodex sir @himanshu251001
