### ISSUE TITLE
HomePage Issue

### ISSUE THREAD

**Issue by himanshu251001** [himanshu251001/E-Commerce#4]
i)Update the UI so that when minimize ,the Css cover the external Links .
ii)Update the UI of login & Signup Page.
![Issue 1](https://user-images.githubusercontent.com/79706463/230787746-d64b7964-42ad-43f5-b0da-f1d7dd72d39d.png)

**Comment by himanshu251001** [comment]
@Chinmayee7697

**Comment by charu1603** [comment]
Please assign me this issue
